#!/usr/bin/env python3
"""Build the native string catalog for the Windows XP target.

Reads every locales/*.json file and writes:
  catalog.rc        one STRINGTABLE per locale (UTF-16LE with BOM, for Microsoft RC)
  catalog.windres.rc  the same tables in ASCII with backslash-x escapes, for GNU windres
  catalog_keys.h    key ids shared by the C code (made from the union of all keys)
  catalog.tsv       the same id -> string table, used by the host unit tests

String id layout, per locale slot i (0 = en, then by "order", then by code):
  base = 1024 + i * 2048
  +0 code  +1 label  +2 name  +3 dir  +4 ui font stack  +5 hero font stack
  +6 numberingSystem  +7 fallback code
  +8..+12  pluralRules for zero, one, two, few, many
  +16 + k*8 + c   plural key k, category c (0 zero .. 5 other); c = 6 holds the
                  exact forms as "N<TAB>text" lines joined by LF
  +160 + k        strings.<key>
  +600 + k        hardware.<key>
  +800 + k        apps: "English name<TAB>local name"
Adding a locale file needs no code change: the program finds locales by
probing slot ids at run time.
"""
import json, os, sys, glob, struct

PLATFORM = 'xp'
CATS = ['zero', 'one', 'two', 'few', 'many', 'other']
BASE, SLOT = 1024, 2048
MAX_PLURALS, MAX_STRINGS, MAX_HW, MAX_APPS = 18, 440, 200, 1000

def main():
    locdir, outdir = sys.argv[1], sys.argv[2]
    os.makedirs(outdir, exist_ok=True)
    locs = []
    for p in sorted(glob.glob(os.path.join(locdir, '*.json'))):
        if os.path.basename(p) == 'schema.json':
            continue
        with open(p, encoding='utf-8') as f:
            d = json.load(f)
        if 'code' not in d:
            continue
        locs.append(d)
    def order(d):
        o = d.get('order', -1 if d['code'] == 'en' else 0)
        return (o, d['code'])
    locs.sort(key=order)
    if len(locs) > 31:
        sys.exit('too many locales for the id layout (31 max)')

    def union(section):
        keys = []
        for d in locs:
            for k in d.get(section, {}):
                if k not in keys:
                    keys.append(k)
        return keys
    skeys, hkeys, pkeys = union('strings'), union('hardware'), union('plurals')
    if len(skeys) > MAX_STRINGS or len(hkeys) > MAX_HW or len(pkeys) > MAX_PLURALS:
        sys.exit('catalog id ranges are full')

    def cid(name):
        return ''.join(c if c.isalnum() else '_' for c in name)

    table = []  # (id, text)
    for i, d in enumerate(locs):
        b = BASE + i * SLOT
        fonts = d.get('fonts', {})
        plat = fonts.get('platforms', {}).get(PLATFORM, {})
        meta = [d['code'], d.get('label', d['code'].upper()), d.get('name', d['code']),
                'rtl' if d.get('dir') == 'rtl' else 'ltr',
                plat.get('ui') or fonts.get('ui') or '', plat.get('hero') or fonts.get('hero') or '',
                d.get('numberingSystem', 'latn'), d.get('fallback', '' if d['code'] == 'en' else 'en')]
        for k, v in enumerate(meta):
            if v:
                table.append((b + k, v))
        for c, cat in enumerate(CATS[:5]):
            r = d.get('pluralRules', {}).get(cat)
            if r:
                table.append((b + 8 + c, r))
        for k, key in enumerate(pkeys):
            forms = d.get('plurals', {}).get(key)
            if not forms:
                continue
            for c, cat in enumerate(CATS):
                if cat in forms:
                    table.append((b + 16 + k * 8 + c, forms[cat]))
            exact = ['%s\t%s' % (f[1:], v) for f, v in forms.items() if f.startswith('=')]
            if exact:
                table.append((b + 16 + k * 8 + 6, '\n'.join(exact)))
        for k, key in enumerate(skeys):
            if key in d.get('strings', {}):
                table.append((b + 160 + k, d['strings'][key]))
        for k, key in enumerate(hkeys):
            if key in d.get('hardware', {}):
                table.append((b + 600 + k, d['hardware'][key]))
        for k, (en, loc) in enumerate(d.get('apps', {}).items()):
            if k >= MAX_APPS:
                break
            table.append((b + 800 + k, '%s\t%s' % (en, loc)))

    for _, s in table:
        if s == '':
            sys.exit('empty strings are not allowed in the catalog')

    def rc_escape(s):
        out = []
        for ch in s:
            if ch == '"': out.append('""')
            elif ch == '\\': out.append('\\\\')
            elif ch == '\t': out.append('\\t')
            elif ch == '\n': out.append('\\n')
            else: out.append(ch)
        return ''.join(out)

    rc = ['// Generated by tools/gen_catalog.py from locales/*.json. Do not edit.',
          'LANGUAGE 0, 0']
    for n, d in enumerate(locs):
        lo, hi = BASE + n * SLOT, BASE + (n + 1) * SLOT
        rc += ['', '// %s (%s)' % (d['code'], d.get('name', d['code'])), 'STRINGTABLE', 'BEGIN']
        for i, s in table:
            if lo <= i < hi:
                rc.append('  %d, L"%s"' % (i, rc_escape(s)))
        rc.append('END')
    # catalog.rc is UTF-16LE with a BOM for Microsoft RC. GNU windres runs the
    # C preprocessor first and cannot read UTF-16 (and mangles UTF-8 inside
    # L"" strings), so it gets an ASCII twin where every other character is a
    # backslash-x escape. Both compile to the same UTF-16 STRINGTABLE.
    with open(os.path.join(outdir, 'catalog.rc'), 'w', encoding='utf-16-le') as f:
        f.write('\ufeff' + '\r\n'.join(rc) + '\r\n')
    def ascii_only(line):
        out = []
        for ch in line:
            if ord(ch) < 128:
                out.append(ch)
            else:
                for unit in struct.unpack('<%dH' % (len(ch.encode('utf-16-le')) // 2), ch.encode('utf-16-le')):
                    out.append('\\x%04x' % unit)
        return ''.join(out)
    with open(os.path.join(outdir, 'catalog.windres.rc'), 'w', encoding='ascii') as f:
        f.write('\r\n'.join(ascii_only(l) if not l.startswith('//') else l.encode('ascii', 'replace').decode() for l in rc) + '\r\n')
    with open(os.path.join(outdir, 'catalog.tsv'), 'w', encoding='utf-8') as f:
        for i, s in table:
            f.write('%d\t%s\n' % (i, s.replace('\\', '\\\\').replace('\t', '\\t').replace('\n', '\\n')))

    h = ['/* Generated by tools/gen_catalog.py from the locale files. Do not edit. */',
         '#ifndef CATALOG_KEYS_H', '#define CATALOG_KEYS_H',
         '#define CAT_BASE %d' % BASE, '#define CAT_SLOT %d' % SLOT,
         '#define CAT_PLURALS 16', '#define CAT_STRINGS 160', '#define CAT_HW 600', '#define CAT_APPS 800',
         '#define CAT_MAX_APPS %d' % MAX_APPS]
    h.append('enum { ' + ', '.join('S_%s = %d' % (cid(k), n) for n, k in enumerate(skeys)) + ', S__COUNT = %d };' % len(skeys))
    h.append('enum { ' + ', '.join('H_%s = %d' % (cid(k), n) for n, k in enumerate(hkeys)) + ', H__COUNT = %d };' % len(hkeys))
    h.append('enum { ' + ', '.join('P_%s = %d' % (cid(k), n) for n, k in enumerate(pkeys)) + ', P__COUNT = %d };' % len(pkeys))
    for name, keys in (('CAT_S_NAMES', skeys), ('CAT_H_NAMES', hkeys), ('CAT_P_NAMES', pkeys)):
        h.append('#define %s { %s }' % (name, ', '.join('"%s"' % k for k in keys)))
    h.append('#endif')
    with open(os.path.join(outdir, 'catalog_keys.h'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(h) + '\n')
    print('catalog: %d locales, %d strings, %d hardware, %d plurals, %d entries' %
          (len(locs), len(skeys), len(hkeys), len(pkeys), len(table)))

if __name__ == '__main__':
    main()
