#!/usr/bin/env python3
"""Builds the embedded C catalog for the Win98 app from locales/*.json.

Usage: gen_catalog.py <locales dir> [<native extras dir>] <out.c>

Every locales/<code>.json becomes one I18nLocaleData record. Strings stay
UTF-8; the app converts them at draw time. For each locale the script also
picks the Windows ANSI code page that can hold all of its text, so the 9x
code path (ExtTextOutA with a charset font) needs no table in code.
"""
import glob
import json
import os
import sys

CATS = ["zero", "one", "two", "few", "many"]

# Code page -> GDI charset value.
CODEPAGES = [
    (1252, 0), (1250, 238), (1251, 204), (1253, 161), (1254, 162),
    (1255, 177), (1256, 178), (1257, 186), (1258, 163), (874, 222),
    (932, 128), (936, 134), (949, 129), (950, 136),
]

# Characters the renderer replaces before ANSI conversion (see src/text.c).
RENDER_SUBST = {0x2068, 0x2069, 0x200E, 0x200F, 0x2212, 0x2190, 0x2191, 0x2192,
                0x2193, 0x2026, 0x00D7, 0x2009, 0x202F, 0x00A0}


def c_str(s):
    if s is None:
        return "0"
    out = []
    for b in s.encode("utf-8"):
        if b == 0x22:
            out.append('\\"')
        elif b == 0x5C:
            out.append("\\\\")
        elif 0x20 <= b < 0x7F and b != 0x3F:  # avoid "??" trigraphs
            out.append(chr(b))
        else:
            out.append("\\%03o" % b)
    return '"' + "".join(out) + '"'


def first_face(stack):
    if not stack:
        return None
    face = stack.split(",")[0].strip().strip('"').strip("'")
    return face or None


def all_text(data):
    for sec in ("strings", "hardware", "apps"):
        for v in (data.get(sec) or {}).values():
            yield v
    for forms in (data.get("plurals") or {}).values():
        for v in forms.values():
            yield v
    for k in ("label", "name"):
        if data.get(k):
            yield data[k]


def pick_codepage(data):
    text = "".join(ch for s in all_text(data) for ch in s if ord(ch) not in RENDER_SUBST)
    best = None
    for cp, cs in CODEPAGES:
        bad = 0
        for ch in set(text):
            try:
                ch.encode("cp%d" % cp)
            except UnicodeEncodeError:
                bad += 1
        if bad == 0:
            return cp, cs, 0
        if best is None or bad < best[2]:
            best = (cp, cs, bad)
    return best


def main():
    if len(sys.argv) == 3:
        loc_dir, out_path = sys.argv[1:]
        extra_dir = None
    elif len(sys.argv) == 4:
        loc_dir, extra_dir, out_path = sys.argv[1:]
    else:
        print(__doc__)
        return 2
    files = sorted(f for f in glob.glob(os.path.join(loc_dir, "*.json"))
                   if os.path.basename(f) != "schema.json")
    lines = ["/* Generated by tools/gen_catalog.py from the locale files. Do not edit. */",
             '#include "i18n.h"', ""]
    names = []
    for path in files:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        if not isinstance(data, dict) or not isinstance(data.get("code"), str):
            continue
        code = data["code"]
        if extra_dir:
            extra_path = os.path.join(extra_dir, code + ".json")
            if os.path.exists(extra_path):
                with open(extra_path, encoding="utf-8") as fh:
                    extra = json.load(fh)
                strings = dict(extra.get("strings") or {})
                strings.update(data.get("strings") or {})
                data["strings"] = strings
        ident = "loc_" + "".join(c if c.isalnum() else "_" for c in code)
        names.append(ident)

        def kv_table(sec):
            items = sorted((data.get(sec) or {}).items(), key=lambda kv: kv[0].encode("utf-8"))
            name = "%s_%s" % (ident, sec)
            if not items:
                lines.append("static const I18nKV %s[1] = { { 0, 0 } };" % name)
                return name, 0
            lines.append("static const I18nKV %s[] = {" % name)
            for k, v in items:
                lines.append("    { %s, %s }," % (c_str(k), c_str(v)))
            lines.append("};")
            return name, len(items)

        s_name, s_n = kv_table("strings")
        h_name, h_n = kv_table("hardware")
        a_name, a_n = kv_table("apps")

        forms = []
        for key, fs in (data.get("plurals") or {}).items():
            for form, tpl in fs.items():
                forms.append((key, form, tpl))
        forms.sort(key=lambda t: (t[0].encode("utf-8"), t[1]))
        p_name = ident + "_plurals"
        if forms:
            lines.append("static const I18nPluralForm %s[] = {" % p_name)
            for key, form, tpl in forms:
                lines.append("    { %s, %s, %s }," % (c_str(key), c_str(form), c_str(tpl)))
            lines.append("};")
        else:
            lines.append("static const I18nPluralForm %s[1] = { { 0, 0, 0 } };" % p_name)

        rules = data.get("pluralRules") or {}
        if not rules:
            # No declared rules: CLDR default for the language is unknown here,
            # so use one/other with "one" for exactly 1 (the engine's last resort).
            rules = {"one": "n = 1"}
        fonts = data.get("fonts") or {}
        plat = (fonts.get("platforms") or {}).get("w98") or {}
        face = first_face(plat.get("ui") or fonts.get("ui"))
        cp, cs, bad = pick_codepage(data)
        if bad:
            sys.stderr.write("warning: %s: %d characters do not fit code page %d\n" % (code, bad, cp))

        lines.append("static const I18nLocaleData %s = {" % ident)
        lines.append("    %s, %s, %s, %s, %d, %s," % (
            c_str(code), c_str(data.get("label") or code.upper()), c_str(data.get("name") or code),
            c_str(data.get("fallback")), 1 if data.get("dir") == "rtl" else 0,
            c_str(data.get("numberingSystem") or "latn")))
        lines.append("    { %s }," % ", ".join(c_str(rules.get(c)) for c in CATS))
        lines.append("    %s, %d, %s, %d, %s, %d, %s, %d," % (
            s_name, s_n, h_name, h_n, p_name, len(forms), a_name, a_n))
        lines.append("    %s, %d, %d, %d" % (c_str(face), cp, cs, data.get("order", -1000)))
        lines.append("};")
        lines.append("")

    lines.append("const I18nLocaleData *const i18n_catalog[] = { %s };" %
                 ", ".join("&" + n for n in names))
    lines.append("const int i18n_catalog_count = %d;" % len(names))
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="ascii") as fh:
        fh.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
