#!/usr/bin/env python3
"""Turns i18n/test/fixtures/vectors.json into a C header for tests/test_i18n.c.

Usage: gen_vectors.py <vectors.json> <out.h>

Sample keys look like "thread:84" (plural key and count) or
"tempLine:cpu=52°C,gpu=48°C" (string key and params).
"""
import json
import sys

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from gen_catalog import c_str  # noqa: E402


def main():
    src, out = sys.argv[1:3]
    with open(src, encoding="utf-8") as fh:
        vec = json.load(fh)
    lines = ["/* Generated by tools/gen_vectors.py. Do not edit. */",
             "typedef struct { const char *loc; const char *n; const char *cat; } CatVec;",
             "typedef struct { const char *loc; const char *key; const char *n;"
             " const char *params; const char *expect; } SampleVec;",
             "static const CatVec cat_vectors[] = {"]
    for loc, body in vec.items():
        for n, cat in body.get("categories", []):
            lines.append("    { %s, %s, %s }," % (c_str(loc), c_str(str(n)), c_str(cat)))
    lines.append("    { 0, 0, 0 }\n};")
    lines.append("static const SampleVec sample_vectors[] = {")
    for loc, body in vec.items():
        for spec, expect in body.get("samples", {}).items():
            key, _, rest = spec.partition(":")
            if "=" in rest:
                lines.append("    { %s, %s, 0, %s, %s }," % (c_str(loc), c_str(key), c_str(rest), c_str(expect)))
            else:
                lines.append("    { %s, %s, %s, 0, %s }," % (c_str(loc), c_str(key), c_str(rest), c_str(expect)))
    lines.append("    { 0, 0, 0, 0, 0 }\n};")
    with open(out, "w", encoding="ascii") as fh:
        fh.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
